# Generated by Django 6.0.4 on 2026-04-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SDE', 'Software Development'), ('DA', 'Data Analyst'), ('QA', 'Quality Assurance'), ('UX', 'UI/UX Designer')], default='SDE', max_length=3)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary_package', models.CharField(help_text='e.g. 12 LPA', max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='jobs.joblisting')),
            ],
        ),
    ]
